//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace New_Trading_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class a_Permission
    {
        public int PermissionID { get; set; }
        public int UserAccountTypeID { get; set; }
        public bool IsShowPrice { get; set; }
        public Nullable<bool> IsShowBid { get; set; }
        public Nullable<bool> IsShowConfig { get; set; }
        public Nullable<bool> IsShowUserConfig { get; set; }
        public Nullable<bool> IsManualEntry { get; set; }
        public Nullable<bool> IsCamSetup { get; set; }
        public string SiteAccess { get; set; }
        public bool IsActive { get; set; }
        public Nullable<bool> IsOperator { get; set; }
    }
}
