//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace New_Trading_API.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MarketMapEntities : DbContext
    {
        public MarketMapEntities()
            : base("name=MarketMapEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<m_EmailRecipient> m_EmailRecipient { get; set; }
        public virtual DbSet<m_FileforProcessing> m_FileforProcessing { get; set; }
        public virtual DbSet<m_FTPConfiguration> m_FTPConfiguration { get; set; }
        public virtual DbSet<m_FTPFiles> m_FTPFiles { get; set; }
        public virtual DbSet<m_FTPFileSheetName> m_FTPFileSheetName { get; set; }
        public virtual DbSet<m_ServiceFTPFileSetup> m_ServiceFTPFileSetup { get; set; }
        public virtual DbSet<m_Services> m_Services { get; set; }
        public virtual DbSet<t_Logs> t_Logs { get; set; }
        public virtual DbSet<vwServiceFTPFileSetup> vwServiceFTPFileSetups { get; set; }
    }
}
