//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace New_Trading_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class m_FileforProcessing
    {
        public int ID { get; set; }
        public Nullable<int> FTPFileID { get; set; }
        public string FIleName { get; set; }
        public Nullable<bool> IsProcessed { get; set; }
        public Nullable<System.DateTime> ProcessedDate { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
    }
}
