//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace New_Trading_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class m_FTPFiles
    {
        public int ID { get; set; }
        public Nullable<int> FTPConfigID { get; set; }
        public string FilePath { get; set; }
        public string UploadFilePath { get; set; }
        public string FilePrefix { get; set; }
        public string FileFormat { get; set; }
        public string FileSuffix { get; set; }
        public string ExtensionName { get; set; }
        public string SheetName { get; set; }
        public Nullable<int> FileperDay { get; set; }
        public string UFLPath { get; set; }
        public string DownloadPath { get; set; }
        public bool IsActive { get; set; }
    }
}
