//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace New_Trading_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class m_ServiceFTPFileSetup
    {
        public int ID { get; set; }
        public Nullable<int> ServiceID { get; set; }
        public Nullable<int> FileID { get; set; }
        public Nullable<System.DateTime> ReadAt { get; set; }
        public string FunctionName { get; set; }
        public Nullable<bool> IsActive { get; set; }
    }
}
