//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace New_Trading_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class m_Unit
    {
        public int UnitID { get; set; }
        public string UnitNumber { get; set; }
        public int SiteID { get; set; }
        public string TypeID { get; set; }
        public string RTDTagName { get; set; }
        public string EAPTagName { get; set; }
        public string DAPTagName { get; set; }
        public string DAPPriceTagName { get; set; }
        public string HAPTagName { get; set; }
        public string HAPPriceTagName { get; set; }
        public string WAPTagName { get; set; }
        public string ActualTagName { get; set; }
        public bool IsActive { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreationDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModificationDate { get; set; }
    }
}
