//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace New_Trading_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class m_UserSiteAccess
    {
        public int AccessID { get; set; }
        public int PermissionID { get; set; }
        public Nullable<int> SiteID { get; set; }
        public Nullable<int> UnitID { get; set; }
    }
}
