//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace New_Trading_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class m_WebServiceURL
    {
        public int WebID { get; set; }
        public string URL { get; set; }
        public string Type { get; set; }
        public bool IsActive { get; set; }
    }
}
