//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace New_Trading_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class m_WebServiceSettings
    {
        public int BidID { get; set; }
        public int UnitID { get; set; }
        public string Operation { get; set; }
        public string CertificateURL { get; set; }
        public string Password { get; set; }
        public string FriendlyName { get; set; }
        public string TpUser { get; set; }
        public string BidType { get; set; }
        public string FileLocation { get; set; }
        public string SheetName { get; set; }
        public bool IsActive { get; set; }
    }
}
