//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace New_Trading_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_Logs
    {
        public int ID { get; set; }
        public Nullable<int> ServiceID { get; set; }
        public string Service { get; set; }
        public Nullable<int> FileID { get; set; }
        public string FileName { get; set; }
        public string SheetName { get; set; }
        public string Type { get; set; }
        public string Message { get; set; }
        public Nullable<System.DateTime> LoggedDate { get; set; }
        public Nullable<bool> IsEmailed { get; set; }
        public Nullable<System.DateTime> EmailedDate { get; set; }
    }
}
