//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace New_Trading_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwServiceFTPFileSetup
    {
        public int ID { get; set; }
        public Nullable<int> ServiceID { get; set; }
        public string ServiceName { get; set; }
        public Nullable<int> Interval { get; set; }
        public string FTPServer { get; set; }
        public string FileAddress { get; set; }
        public string UploadFilePath { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public Nullable<int> FileID { get; set; }
        public string ExtensionName { get; set; }
        public string FunctionName { get; set; }
        public string UFLPath { get; set; }
        public string DownloadPath { get; set; }
    }
}
